### ISSUE TITLE
[BungeeCord] ViaVersion kicking players for too many plugin messages

### ISSUE THREAD

**Issue by SrMonsterYT** [NEZNAMY/TAB#1211]
### Server version

waterfall 1.20.4

### TAB version

4.1.2

### Describe the bug

there's a big bug when I use TAB in bungeecord, each of my servers has an animated TAB and every time I add it I have to keep increasing its update time so it doesn't kick me out for sending too many packets or deleting animations and this didn't happen when it was individual, watch

this video: https://www.youtube.com/watch?v=phJGdgg0H2w

sorry the video is so long but I managed to show the bug, please watch and tell me if there is a solution for this without having to remove the animations

server versions:
lobby 1.12.2 ( bug only occurs in lobby version 1.12.2 )
bungeecord 1.20.3
survival 1.20.1

I'm using TAB version 4.1.2
TAB-Bridge version: 5.0.1

i removed all animation from the lobby and left it on the other servers, but whenever i go to the lobby i get kicked for sending too many packets and the lobby is on 1.12.2, this never happened when it was the individual TAB, is there a solution for this? do you have a discord so i can send you more information there?

i found out that the problem is in viaversion could you tell me why this happens, i disabled the option in viaversion:
tracking-max-warnings: -1

this only happens with 1.12.2 servers

### Expected behavior

no kick player

### Steps to reproduce

use TAB in bungeecord, and set up several animations per server, then you'll be kicked by viaversion for sending too many packages.

each scoreboard on each server must have its own animations

### Additional info

if there was support for synchronizing 2 servers using mysql or redis this would solve all the problems, just putting in the bungeecord option and having to change the whole networks tab is a lot of work

add support for mixed installation, allow me to ignore the servers I want and use the plugin on both bungeecord and spigot.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I ticked all of the boxes without actually reading them
- [X] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [X] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
![image](https://github.com/NEZNAMY/TAB/assets/6338394/d3e34975-91c7-4e76-af21-0c85fefb7bbd)
Get latest build from [actions](https://github.com/NEZNAMY/TAB/actions) and set `register-tab-expansion: false`.

**Comment by SrMonsterYT** [comment]
> ![image](https://private-user-images.githubusercontent.com/6338394/296503560-d3e34975-91c7-4e76-af21-0c85fefb7bbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMjQ1NzksIm5iZiI6MTcwNTMyNDI3OSwicGF0aCI6Ii82MzM4Mzk0LzI5NjUwMzU2MC1kM2UzNDk3NS05MWM3LTRlNzYtYWYyMS0wYzg1ZmVmYjdiYmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTVUMTMxMTE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjlkYzg5MTkxOWMxMDA0OGJjZWEwNzY4MTkwNDUwZDRkY2U1N2ZkMmU1ZGUyMzc5ODE1NjI2MzlkM2Q0ZGNkOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.RbVYSuLSvQd4dbxBl2sf4CsgZmM2ovwtXYCf8FiYNT4) Get latest build from [actions](https://github.com/NEZNAMY/TAB/actions) and set `register-tab-expansion: false`.

is for me to use TAB-4.1.3-SNAPSHOT

and where do I find the register-tab-expansion option?

I can't find anything in the tab configuration

**Comment by NEZNAMY** [comment]
Did you update? The option was added in dev builds.

**Comment by SrMonsterYT** [comment]
> Did you update? The option was added in dev builds.

just change the jar and the option will go into the settings by itself?

**Comment by NEZNAMY** [comment]
Yes, like magic.

**Comment by SrMonsterYT** [comment]
deactivating this option stops the tab working and this error appears: https://prnt.sc/-J10XopsFNRo

**Comment by NEZNAMY** [comment]
Update to latest build.

**Comment by SrMonsterYT** [comment]
solved, but this console appears: https://prnt.sc/y56r7czHq6Wz

**Comment by NEZNAMY** [comment]
That's a warn supposed to hint you that sorting may not work as expected due to group assigning not working properly, most likely due to wrong configuration. That message is not a bug that should be fixed or anything.

**Comment by NEZNAMY** [comment]
What does classifying groups by server mean? 
If you have global playerlist enabled, the game will tabcomplete all players in the tablist, including those on other servers if enabled.

**Comment by SrMonsterYT** [comment]
when i tabbed to bungeecord the %health% placeholderAPI didn't work what could it be?

command: btab group _DEFAULT_ belowname %health%

can you create groups for each belowname and abovename?

**Comment by NEZNAMY** [comment]
%health% is not a PlaceholderAPI placeholder. That's why it doesn't work. Not a bug. Please only use the issue tracker for reporting issues in the plugin.

**Comment by SrMonsterYT** [comment]
> btab group _DEFAULT_ belowname %health%

https://prnt.sc/ZPEbLw9IZOoY

I activated debug and typed /btab reload and this appeared but it still shows %health%

**Comment by NEZNAMY** [comment]
I already told you this is not a PlaceholderAPI placeholder and therefore you cannot use it on BungeeCord.

**Comment by SrMonsterYT** [comment]
everything is going well <3

**Comment by SrMonsterYT** [comment]
the tab in the lobby that is in 1.12.2 is leaving the players' tags in place, if I stand in the lobby of 1.12.2 and players enter it keeps creating several and several tags and leaving them in place, after going to survival 1.20.4 and back they disappear, but if I stand there in the lobby there are 1 lot of tags like this see: 

https://prnt.sc/idOOXa1BSgjN

**Comment by NEZNAMY** [comment]
Did you get error file in TAB's folder?

**Comment by SrMonsterYT** [comment]
[errors.log](https://github.com/NEZNAMY/TAB/files/14030375/errors.log)

**Comment by SrMonsterYT** [comment]
> -XX:-OmitStackTraceInFastThrow

my start.bat: java -Xms1G -Xmx4G -XX:+UseG1GC -XX:G1HeapRegionSize=4M -XX:+UnlockExperimentalVMOptions -XX:+ParallelRefProcEnabled -XX:+AlwaysPreTouch -Djava.awt.headless=true --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED -jar server.jar

how do I add it

**Comment by NEZNAMY** [comment]
You have several parameters starting with `-XX`, add it between them.

**Comment by SrMonsterYT** [comment]
the problem still occurs, if I leave the lobby they disappear but if I stay there they appear again every time a player enters 

https://prnt.sc/f9VEkpldR852

**Comment by NEZNAMY** [comment]
So they don't disappear when their owners leave the server? Did you get error file again?

**Comment by SrMonsterYT** [comment]
> So they don't disappear when their owners leave the server? Did you get error file again?

my players are being kicked and this error appears: https://prnt.sc/ZMlJUa7w3N9Q

the tab plugin also generated this error: 
[errors.log](https://github.com/NEZNAMY/TAB/files/14040608/errors.log)

also this error: https://prnt.sc/KZN9tydaLsNF

**Comment by NEZNAMY** [comment]
I will need full paste of the bungeecord error, not just a screenshot that cuts the most important part.

**Comment by SrMonsterYT** [comment]
> I will need full paste of the bungeecord error, not just a screenshot that cuts the most important part.

https://mclo.gs/WlWoa4G

**Comment by NEZNAMY** [comment]
Try new build. This error should however not cause a disconnect.

**Comment by NEZNAMY** [comment]
You need to wait for github to compile it. The plugin is big and takes forever to compile.

**Comment by SrMonsterYT** [comment]
it's no longer kicking players, but the tag problem is still there, it happens in the 1.12.2 lobby, in the 1.20.1 survival lobby it doesn't happen.

https://prnt.sc/AYOvs3vsjvZb

**Comment by NEZNAMY** [comment]
Could it be that on the 1.20.1 server you don't have unlimited nametags on? 
Is the issue that they don't disappear when players quit? Can you set `debug: true` in config and show console output when a player quits, but their armor stands stay?

**Comment by SrMonsterYT** [comment]
> Could it be that on the 1.20.1 server you don't have unlimited nametags on? Is the issue that they don't disappear when players quit? Can you set `debug: true` in config and show console output when a player quits, but their armor stands stay?

I'm using TAB in bungeecord

debug true: https://prnt.sc/hGo7rue8z5Gz

**Comment by NEZNAMY** [comment]
Could it be that you set disable-condition the way that on the 1.20.1 server it is off? 
The log you sent is not on quit, is it? But since you have TAB on bungeecord it wouldn't help anyway.

**Comment by SrMonsterYT** [comment]
> Could it be that you set disable-condition the way that on the 1.20.1 server it is off? The log you sent is not on quit, is it? But since you have TAB on bungeecord it wouldn't help anyway.

do you have discord so I can send you my complete TAB folder just so I don't publish it here for everyone?
my discord: mauriciooficial

**Comment by NEZNAMY** [comment]
Customer discord is only for customers. Are you a customer?

**Comment by SrMonsterYT** [comment]
> Customer discord is only for customers. Are you a customer?

I'm not, I didn't even know discord existed for buyers, but what's wrong with this case? I'm using TAB in bungeecord

**Comment by NEZNAMY** [comment]
I don't know why is it happening. I would need exact steps to reproduce this issue, just like any bug report.

**Comment by SrMonsterYT** [comment]
> I don't know why is it happening. I would need exact steps to reproduce this issue, just like any bug report.

I don't know either, I just know that you have to stand in the lobby which is in 1.12.2 and wait, every 10 - 20 players 1 lets the tag stay.

**Comment by NEZNAMY** [comment]
So when a player leaves, there's a small chance armor stands stay? Can you try on a test server with no other plugins?

**Comment by SrMonsterYT** [comment]
> So when a player leaves, there's a small chance armor stands stay? Can you try on a test server with no other plugins?

I'd have to create 1 bungeecord server, and create lots and lots of accounts and keep logging in and out, it would be very difficult to achieve this, here on the main server about 10 players enter every 30 minutes

**Comment by NEZNAMY** [comment]
And it's easy for me to do?

**Comment by SrMonsterYT** [comment]
> And it's easy for me to do?

no, unfortunately I don't know how to fix it, it happened when I put in this new version

**Comment by NEZNAMY** [comment]
Since unlimited nametags on proxy are managed by bridge, updating the main plugin could not have caused it.

**Comment by NEZNAMY** [comment]
[Unable to reproduce](https://www.youtube.com/watch?v=bV0AyNeOCu0). Tried on both 1.12.2 and 1.20.1, both worked fine.

**Comment by SrMonsterYT** [comment]
> [Unable to reproduce](https://www.youtube.com/watch?v=bV0AyNeOCu0). Tried on both 1.12.2 and 1.20.1, both worked fine.

yes, as I said every 15 - 20 players 1 lets the tag stay, and you have to stand there waiting in the lobby for the players to enter still

**Comment by NEZNAMY** [comment]
I spawned in 100 bots, that should be enough. For bridge it's just leaving the server, backend doesn't see the concept of switching servers.

**Comment by SrMonsterYT** [comment]
when i leave the lobby and come back it disappears, is it a visual bug of the player? it happened to 2 players

**Comment by NEZNAMY** [comment]
It means the entity destroy packet was not sent to you and I don't know why.

**Comment by SrMonsterYT** [comment]
a player just reported that 1 player's tag was left on his land, I asked him to relog and it disappeared, and only he could see it, in version 1.20.1

https://prnt.sc/UxpH-J7T_9O3

**Comment by NEZNAMY** [comment]
I know it disappears on reconnect. There is no reason for it not to disappear. The problem is that for some reason it is not removed when it should be.

**Comment by SrMonsterYT** [comment]
this only happens when I put it on the Bungeecord, could it be that the problem isn't with the TAB - Bridge?

**Comment by NEZNAMY** [comment]
Unlikely, despawning logic on quit is handled by bridge.

**Comment by SrMonsterYT** [comment]
> Unlikely, despawning logic on quit is handled by bridge.

any suggestions on how this can be solved?

**Comment by NEZNAMY** [comment]
By finding steps to reproduce that will work for me.

**Comment by SrMonsterYT** [comment]
some players complain to me that when they enter the server they get kicked, and I get this message on the bungeecord console:

https://prnt.sc/1kocZZWAFAsl

my config: https://mclo.gs/Zw5mIJe

**Comment by NEZNAMY** [comment]
This team was [not created by TAB](https://github.com/NEZNAMY/TAB/wiki/Additional-information#scoreboard-objective-and-team-naming). Please refrain from reporting bugs in other plugins here.

**Comment by SrMonsterYT** [comment]
> This team was [not created by TAB](https://github.com/NEZNAMY/TAB/wiki/Additional-information#scoreboard-objective-and-team-naming). Please refrain from reporting bugs in other plugins here.

sorry i didn't understand, did i do something wrong or do i have to open another report about this bug?

Is there a fix for this bug? 
my server is 1.8 - 1.20.4

**Comment by SrMonsterYT** [comment]
> I literally told you this is a bug in another plugin and I am not fixing those.

but I've never had this bug, it only happened when I added TAB to bungeecord, and TAB is the only plugin on my server that deals with scoreboards.

**Comment by NEZNAMY** [comment]
It clearly isn't. Another plugin created that team.

**Comment by SrMonsterYT** [comment]
this doesn't make any sense, I've never seen this error, it only happens when TAB has been added to the bungeecord, is there any way of knowing?

i remember mcmmo used to create scoreboards like this but i don't use mcmmo

is there any way of detecting what it is?

**Comment by NEZNAMY** [comment]
Unfortunately there is no simple way to find out. The only way I can think of isi creating a mini plugin using ProtocolLib to create a sync packet listener and print stack trace on team packet. I am, however, not going to do this as this has nothing to do with TAB.

**Comment by SrMonsterYT** [comment]
> Unfortunately there is no simple way to find out. The only way I can think of is creating a mini plugin using ProtocolLib to create a sync packet listener and print stack trace on team packet. I am, however, not going to do this as this has nothing to do with TAB.

but i only get this error because of the TAB i've never seen this error in my life

if you create it I could tell you what it is so you can even put in your GUIDE the name of the plugin that will cause conflicts

this could help people who use TAB

**Comment by NEZNAMY** [comment]
The wiki is already big enough that people refuse to read it and ask for help directly instead. The list of teams of other plugins only contains the most common ones and this is the first time I see this name pattern. Like I said, I am not interested in making that plugin.
If you still don't believe, can you temporarily remove TAB and try if you get the kick again?

**Comment by SrMonsterYT** [comment]
I activated the TAB debug option and when the player entered, other players were also mentioned, see:

https://prnt.sc/sIlW557tAGv4

**Comment by NEZNAMY** [comment]
You just sent another screenshot of the same error that isn't caused by TAB.

**Comment by SrMonsterYT** [comment]
> You just sent another screenshot of the same error that isn't caused by TAB.

I use waterfall, and this happens when I log into the 1.20.1 server, and I don't have any TAB or scoreboard plugins, the only one I use is yours

**Comment by NEZNAMY** [comment]
Like I said, uninstall TAB if you believe it's causing this error to find out.

**Comment by SrMonsterYT** [comment]
I've been using this plugin for years, removing it doesn't make sense, it would be perfect if one day you added support for mysql to be able to synchronize the same tab on 2 servers than in bungeecord, every time I add a new server I have to change all the servers, or add an option that ignores that server so I can put the individual TAB on that server, I've been using this plugin for years I've never had any problems, it was just adding it to bungeecord that started, I know you do your best for this plugin but you should add more options, add the mixed option as a premium version and I would buy it myself

**Comment by NEZNAMY** [comment]
MySQL is supported.
Premium version was out for 3 years. You had plenty of time to buy it.
I am talking about temporarily removing it for a couple of minutes until the error appears again and then add it back.

**Comment by SrMonsterYT** [comment]
> MySQL is supported. Premium version was out for 3 years. You had plenty of time to buy it. You were not interested. I am talking about temporarily removing it for a couple of minutes until the error appears again and then add it back.

but mysql doesn't synchronize servers right? and yes i didn't buy it because i didn't need to synchronize 2 servers now i do.

this error happens to 1 player out of 60, yesterday it happened to 1 different player, today to another.

**Comment by NEZNAMY** [comment]
What do you mean by synchronizing? Global playerlist? MySQL is a database, using it for such feature would be a horrible thing. Either way [feature requests are closed](https://github.com/NEZNAMY/TAB?tab=readme-ov-file#provided-services).

**Comment by SrMonsterYT** [comment]
> What do you mean by synchronizing? Global playerlist? MySQL is a database, using it for such feature would be a horrible thing. Either way [feature requests are closed](https://github.com/NEZNAMY/TAB?tab=readme-ov-file#provided-services).

I had to change the entire tab of my network because of the TAB synchronization, if I had the mixed option it would be incredible or the TAB to be added in the bungeecord plus have how to control it by the server and list which server would be applied the synchronization by the tab would be better, and less confusing

**Comment by NEZNAMY** [comment]
Feature requests are closed.
