### ISSUE TITLE
TAB installed on FlameCord proxy is not connected to TAB-Bridge on servers after updating to 1.21.7

### ISSUE THREAD

**Issue by LordOfDeUniverse** [NEZNAMY/TAB#1514]
### Server version

FlameCord - Update 2.4.4 (MC 1.21.7 Support)

### TAB version

5.2.4 and 5.2.5 Snapshot

### Plugin list

On proxy:
TAB, Maintenance, Bungeeguard, VentureChat

On the server:
AdvancedHelp, ArmorStandEditor, *AutoBroadcast, AxiomPaper, BanAnnouncer, BungeeGuard, BuycraftX, ChestSort, Chunky, ColoredAnvils, ColoredSigns, CoordinatesHud, CoreProtect, DiscordSRV, DiscordSRV-Staff-Chat, DiscordWhitelister, DoubleShulkerShells, EntityDetection, Essentials, EssentialsSpawn, FastLeafDecay, GSit, HeadDatabase, *HideStream, LiteBans, LoneLibs, LuckPerms, Maintenance, MinecraftStats, OpenInv, OreAnnouncer, PetNameFix, PlaceholderAPI, PremiumVanish, ProtocolLib, Redye, SilenceMobs, SinglePlayerSleep, Skript, Spicord, squaremap, squaremap-deathspot, squaremap-signs, StopVinesGrowing, SurvivalDisplay, TAB, TAB-Bridge, Vault, VentureChat, voicechat, Votifier, VotingPlugin, *Welcome, WorldBorder, WorldEdit, WorldGuard

### Describe the bug

When I updated the plugins to their latest version for 1.21.7 update. TAB didn't work, the prefixes and suffixes don't appear, they are not connecting with the PAPI hooks, i.e. %vault-prefix%[Name]%essentials_afk%.
After running /btab debug, everything seems fine except that it says "[TAB]: Bridge connection: Not connected (requires Bridge version 6.x.x installed)".
The Tab-Bridge version is 6.0.3, I also tried 6.0.2 and it didn't work either.

### Expected behavior

The names on TAB to appear right.

### Steps to reproduce

Step 1: Get TAB 5.2.5 - SNAPSHOT or TAB 5.2.4 on 1.21.7 on a proxy server.
Step 2: Get TAB-Bridge 6.0.3 or 6.0.2 on 1.21.7 on a server connected to the proxy.
Step 3: Start the servers.

### Additional info

I am not sure if it is not a TAB-Bridge issue since it is the connection between both. TAB works fine alone when it is not downloaded on the proxy.

### Checklist

- [x] I am running latest version of the plugin
- [x] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [x] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [x] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Bridge 6.0.2 will throw errors on paper 1.21.7. This was fixed in 6.0.3. Are you sure you are not getting any errors in the backend console?

**Comment by LordOfDeUniverse** [comment]
https://pastebin.com/aCyCbXMK

No errors.

**Comment by NEZNAMY** [comment]
I meant on backend. You sent proxy log.

**Comment by LordOfDeUniverse** [comment]
My bad, here you go, still don't see any errors

https://pastebin.com/6ZJ0UiLu - tab bridge 6.0.3

https://pastebin.com/x6yUn6WX - tab bridge 6.0.2

**Comment by NEZNAMY** [comment]
I'll try it out tomorrow.

**Comment by NEZNAMY** [comment]
I tested it and it turns out paper changed something in 1.21.7. Well, something else besides the change that required a bridge update. Now, when sending plugin messages from proxy, the backend (bridge) does not receive the event at all. It works fine on 1.21.6.
I will try to look into the cause and possible workaround for this.

Edit 1: It may or may not be caused by commits around https://github.com/PaperMC/Paper/commit/6ea679eb07209eecdd14a14c480e72bbecc87444, I assume it's because I am sending plugin messages too early in configuration phase and since 1.21.7, paper has changed the way we can listen to that?

I also tried on Velocity and thankfully at least there it works. That's probably because I am listening to a Velocity event that's called after player is fully connected and configuration phase finished.

**Comment by NEZNAMY** [comment]
@LordOfDeUniverse try latest build of bridge from https://github.com/NEZNAMY/TAB-Bridge/actions

**Comment by LordOfDeUniverse** [comment]
I don't think I can download it since it says the build failed

**Comment by NEZNAMY** [comment]
Oops, fixed now.

**Comment by LordOfDeUniverse** [comment]
Just tried it and it seems it is still bugged, tried /btab debug on the proxy and got the same outcome. Running on the TAB 5.2.5 SNAPSHOT

**Comment by NEZNAMY** [comment]
Are you sure you replaced the jar correctly? The name didn't change, so it can be confusing.

**Comment by LordOfDeUniverse** [comment]
https://pastebin.com/4F48H9MK - Proxy/frontend log

https://pastebin.com/QUnLATQ8 - backend log

**Comment by LordOfDeUniverse** [comment]
I am 99.9% sure since the file size is bigger for the new one

**Comment by NEZNAMY** [comment]
Can you join the discord linked in readme? I will send you jar(s) to test.
