### ISSUE TITLE
belowname-objective placeholder display bug

### ISSUE THREAD

**Issue by Stabrinai** [NEZNAMY/TAB#1533]
### Server version

Velocity 3.4.0-SNAPSHOT (git-38490640)

### TAB version

5.2.5

### Plugin list

Velocity
```log
plugins: velocity, vpacketevents, luckperms, authmevelocity, commandwhitelist, epicguard, libertybans, mapmodcompanion, signedvelocity, simplepay, skinsrestorer, synccommand, velocity-scoreboard-api, tab, viaversion, viabackwards
```

Folia backend ver1.21.8
```log
? Server Plugins (42):
Paper Plugins (1):
 - SignedVelocity
Bukkit Plugins (41):
 - afk, ArmorStandEditor, BetterItemFrame, BetterRTP, CarryEntity, CMI, CMILib, CommandPrompter, CommandWhitelist, CoreProtect
 ExtraContexts, FarmControl, FKBoom, GreenChunk, GrimAC, GSit, LuckPerms, MapModCompanion, packetevents, PersonalPhantoms
 PlaceholderAPI, PlayerPoints, PvPManager, RayTraceAntiXray, RedisChat, SendMiniMessage, Signature, SimpleTools, SpectatorFunction, SyncCommand
 TAB-Bridge, TimeIsMoney, Topper, Towny, UniversalCauldron, Vault, ViaBackwards, ViaVersion, zAuctionHouseV3, zMenu
 zShop
```

### Describe the bug

The plugin does not display placeholder correctly and displays them as 0.

### Expected behavior

Correctly display placeholder values.

```yml
belowname-objective:
  enabled: true
  value: '0'
  title: '&a[小时]'
  fancy-value: '%statistic_hours_played%'
  fancy-value-default: '##'
  disable-condition: '%server%=lobby'
```

### Steps to reproduce

I don't know, but some people show normal, some people show 0, and it's the same every time I reload.

### Additional info

Showing 0 screenshots
<img width="2560" height="1351" alt="Image" src="https://github.com/user-attachments/assets/ffb1bd45-0219-4e51-8e31-b1ed3dcfa268" />

Normal player screenshots
![Image](https://github.com/user-attachments/assets/f9e4478f-be39-47d3-9b7c-c982803bd280)

### Checklist

- [x] I am running latest version of the plugin
- [x] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them
- [x] I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
- [x] I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds

**Comment by NEZNAMY** [comment]
Are you sure you are using 1.20.3+ and NOT lunar / feather client?

**Comment by Stabrinai** [comment]
> Are you sure you are using 1.20.3+ and NOT lunar / feather client?

1.21.8 Fabric

**Comment by NEZNAMY** [comment]
Does /tab reload fix it or not?

**Comment by Stabrinai** [comment]
> Does /tab reload fix it or not?

There is no repair, it can only fix some people, but at the same time it will cause problems for other people.

**Comment by NEZNAMY** [comment]
So reload can actually break it for someone? Can you make a video of that?

**Comment by Stabrinai** [comment]
> So reload can actually break it for someone? Can you make a video of that?

https://www.youtube.com/watch?v=HXUpgSitxUU

At the beginning of the video, some players will display the NPC's value "##"

**Comment by NEZNAMY** [comment]
I think I know the cause. Can you check `/btab parse <player> %world%` on you and the player without value? Folia never calls world change event, so bridge doesn't forward this value properly and it needs to be fixed.

**Comment by NEZNAMY** [comment]
Try latest build of bridge from https://github.com/NEZNAMY/TAB-Bridge/actions

**Comment by Stabrinai** [comment]
<img width="2560" height="1351" alt="Image" src="https://github.com/user-attachments/assets/bd8af6db-7d26-4218-8d09-854e3e750be2" />

The player is at world_the_end, but the returned %world% value is world_nether

**Comment by Stabrinai** [comment]
> I think I know the cause. Can you check `/btab parse <player> %world%` on you and the player without value? Folia never calls world change event, so bridge doesn't forward this value properly and it needs to be fixed.

When TAB is reloaded, it shows 0, but %world% shows world_the_end
<img width="2560" height="1351" alt="Image" src="https://github.com/user-attachments/assets/6d8e26f7-a110-437f-b24e-ecee51a70258" />

**Comment by Stabrinai** [comment]
> Try latest build of bridge from https://github.com/NEZNAMY/TAB-Bridge/actions

Thanks, I'll test it tomorrow

**Comment by Stabrinai** [comment]
The placeholder values are now displayed correctly, but a large number of players are marked as NPCs.

<img width="437" height="314" alt="Image" src="https://github.com/user-attachments/assets/5eccb4df-f6ec-48e0-b84c-504b6ee5346e" />

<img width="579" height="548" alt="Image" src="https://github.com/user-attachments/assets/64fa498e-42eb-40b5-bd40-f291e7eef76c" />

<img width="954" height="635" alt="Image" src="https://github.com/user-attachments/assets/293f102d-e11c-45b1-a319-f2e5249742f7" />

/btab parse player %statistic_hours_played% returns a normal value, but is displayed as ##


Reloading will still fix some people's placeholders, but will break some people's placeholders

**Comment by Stabrinai** [comment]
It seems there are still problems

<img width="975" height="488" alt="Image" src="https://github.com/user-attachments/assets/d9a42a43-87cd-4926-af4d-cb667ff5b723" />

<img width="1028" height="617" alt="Image" src="https://github.com/user-attachments/assets/70f1a1d5-5fe8-40bd-ba3d-f0c8d4cf3b94" />

**Comment by NEZNAMY** [comment]
Can you check if `/btab parse <player> %world%` shows the correct world for both you and the target player?

**Comment by Stabrinai** [comment]
> Can you check if `/btab parse <player> %world%` shows the correct world for both you and the target player?

<img width="2560" height="1351" alt="Image" src="https://github.com/user-attachments/assets/3d6235ac-4823-4ece-9704-337e7ab9740d" />

<img width="2560" height="1351" alt="Image" src="https://github.com/user-attachments/assets/d5080fc8-fc25-42a6-9f39-0fe15de13d78" />

When I saw him, it showed 0, but when I teleported to another dimension and then teleported back, it restored

**Comment by Stabrinai** [comment]
<img width="2560" height="1351" alt="Image" src="https://github.com/user-attachments/assets/56a5bbd9-612c-4bf8-b63c-54fba0d7de0e" />

When I re-entered the server...it broke again

**Comment by Stabrinai** [comment]
https://youtu.be/AB1N8VMKmBg

**Comment by NEZNAMY** [comment]
You forgot to show output of `/btab parse <player> %world%` for both you and the target player with incorrect display.

**Comment by Stabrinai** [comment]
> You forgot to show output of `/btab parse <player> %world%` for both you and the target player with incorrect display.

<img width="2560" height="1351" alt="Image" src="https://github.com/user-attachments/assets/b12b2f7c-e320-4dfd-9b0d-3149a822fc9c" />

<img width="2560" height="1351" alt="Image" src="https://github.com/user-attachments/assets/4a6a0202-f081-497f-ad06-1769d77ce422" />

**Comment by Stabrinai** [comment]
Sorry, I found the reason. Because the Folia I used was modified and the teleportation API was added, but the PlayerWorldChangeEvent was triggered before the player was teleported to the new dimension, so there was a synchronization problem. But I have solved it by listening to PlayerTeleport.
```java
    @EventHandler
    public void onWorldChange(@NonNull PlayerTeleportEvent e) {
        if (e.getTo() != null && e.getFrom().getWorld() == e.getTo().getWorld()) return;
        BridgePlayer p = TABBridge.getInstance().getPlayer(e.getPlayer().getUniqueId());
        if (p == null) return;
        p.sendPluginMessage(new WorldChange(e.getTo().getWorld().getName()));
    }
```

This method is not valid for the original branch Folia... I only solved my problem here... But I can help test the problem on the original branch Folia

**Comment by NEZNAMY** [comment]
But I have fixed it in the latest Bridge build I linked. Did you update correctly?

**Comment by Stabrinai** [comment]
> But I have fixed it in the latest Bridge build I linked. Did you update correctly?

Yes, I just tested it and it's fixed, thanks!

**Comment by NEZNAMY** [comment]
What??? You've been posting despite not using the jar I asked you to use?

**Comment by Stabrinai** [comment]
> What??? You've been posting despite not using the jar I asked you to use?

I used it as soon as you posted it, but I still have the problem. I think it may be related to my Folia modification.

**Comment by Stabrinai** [comment]
> What??? You've been posting despite not using the jar I asked you to use?

Well, my modified Folia was firing the PlayerWorldChangeEvent correctly, but the refreshWorld() method only calculated the difference between the player's current world and the world in the BridgePlayer instance. In fact, if they were equal, nothing was done. However, teleporting triggered the PlayerWorldChangeEvent and also triggered the refreshWorld() method, effectively running sendPluginMessage(new WorldChange(world)) twice, thus causing this issue.

**Comment by NEZNAMY** [comment]
How can running it twice cause the issue? There's a check to make sure it doesn't send the plugin message if world didn't change. Even if it did, TAB should handle it properly. I am still confused.

**Comment by Stabrinai** [comment]
> How can running it twice cause the issue? There's a check to make sure it doesn't send the plugin message if world didn't change. Even if it did, TAB should handle it properly. I am still confused.

Well, refreshWorld() compares the player's current world with the world stored in BridgePlayer. When the player switches dimensions, the player's current world changes, updating the world stored in BridgePlayer and running 
```java
sendPluginMessage(new WorldChange(world))
```
, but only once, because the player's current world and the world stored in BridgePlayer are equal. However, my modified Folia listens for PlayerWorldChangeEvent and runs 
```java
p.sendPluginMessage(new WorldChange(e.getPlayer().getWorld().getName()));
```
, and the world sent in PlayerWorldChangeEvent is the wrong world...

**Comment by NEZNAMY** [comment]
Why is the world wrong and why does it matter? Could it be that somehow the event is executed more than 1 tick later, causing it to overwrite the correct world sent by the periodic task?

**Comment by Stabrinai** [comment]
This should be the case. I feel that there is a problem with the Folia I modified. I have tested the plug-in on the original branch Folia and there is no problem.
